### ISSUE TITLE
Provide a way to reorder tasks

### ISSUE THREAD

**Issue by vvo** [todotxt/todo.txt-cli#137]
Is there a way from the command line to reorder tasks in the todo file?

Like every (A) tasks would be moved to top of file, same for every other priorities.

**Comment by shariqmus** [comment]
alias tl='todo.sh list | sort'

**Comment by inkarkat** [comment]
As this old issue got resurrected, but so far has received only various short suggestions, some clarifications:

`todo.sh list` itself does sorting, and this can be influenced via the `TODOTXT_SORT_COMMAND` environment variable. The default command is `sort -f -k2`; i.e. case-insensitive sorting starting with column 2 (the first column is the task number during todo processing). This means that tasks are listed by priority A, B, C, ... and then unprioritized. (If unprioritized tasks start with some strange characters (e.g. `#`), these may appear even _before_ the prioritized ones, but this is unlikely to happen (and could be fixed by tweaking the sort command).)

To reconfigure the sorting permanently, define the variable in the configuration file (e.g. `todo.cfg`). You can also temporarily override the sorting by prepending it:

    $ TODOTXT_SORT_COMMAND='sort --reverse -k2' todo.sh ls

---

Now, what the original submitter really asked for is a _permanent_ change in the order of the tasks. Based on the above explanation, this should **not be necessary**, and is not recommended. `todo.sh` and other todo apps can do sorting, so the original order (of submission) should be kept stable. But hey, maybe you have a stupid widget that can only display text files as-is.

What does **not** work is redirecting the output of `todo.sh list` back into the file; first because line numbers are introduced and second you should not directly redirect output back to its source.

However, as one answer already indicated, any text editor (like Vim) can be used to modify the order. If you want an automated solution on the command-line, `sort` will work just fine (provided the second issue is handled):

    $ sort -f -k2 ~/todo/todo.txt | sponge ~/todo/todo.txt
