### ISSUE TITLE
[Request] Owncloud/Nextcloud support

### ISSUE THREAD

**Issue by apastuszak** [todotxt/todo.txt-cli#195]
I would love to see support for personal cloud services such as owncloud/Nextcloud.

**Comment by vascowhite** [comment]
Support in what way? I think you'll need to be a bit more specific.

**Comment by apastuszak** [comment]
Use Nextcloud to sync on the mobile app the way it uses Dropbox now.

**Comment by vascowhite** [comment]
I use owncloud, which is the same. I just keep my todo.txt files in a folder synched by owncloud, point todo.sh and its config file at them and there you go. I think I had to setup a symlink somewhere, but it was a long time ago and has worked faultlessly since on all my machines with the same todo.txt file shared between them. I hope that helps.

**Comment by apastuszak** [comment]
And this works on phones and tablets also?

**Comment by vascowhite** [comment]
Not with the apps available on iOS as they don't support webdav, but you'd have to raise that with the app developers directly. I just edit the test file directly in the owncloud app, it isn't great, but it does the job.
