### ISSUE TITLE
[Support] Syncing: multiple .cfg's for multiple machines?

### ISSUE THREAD

**Issue by jarmitage** [todotxt/todo.txt-cli#201]
I have Todo.txt running on my main laptop and synchronised via Dropbox.

I have just set up another laptop and synchronised to the same Dropbox.

My current problem is that both laptops have different names, but both share the same `.cfg`, which means the new machine has incorrect directories etc and therefore isn't running in the CLI.

Should I:
- Have separate `.cfg` for each laptop (outside of Dropbox), and link them to the same `todo.txt` (inside Dropbox)?
- Make all paths in `.cfg` relative and the same across both laptops?
- Something else?

Thanks

**Comment by craigmaloney** [comment]
Is the laptop a UNIX / Linux-based laptop? If so you may be able to get away with using soft-links to the directory in question.

Barring that I would recommend a separate .cfg file for each machine. But that's personal preference.

**Comment by mmccarn** [comment]
I put a file in my home folder on all workstations named ".todo.sh", then call that from whatever file my system runs on login (eg .bash_profile for cygwin or mac)

This lets me share the same todo.cfg and todo.sh and all settings between my windows computers at work (using cygwin), at home - with a different username - using either cygwin or ubuntu-on-windows, and on my mac laptop.

All the system-specific info goes into the ".todo.sh" file, which is stored outside of Dropbox so that changes on one system won't break another.

**Cygwin**

~/.bash_profile - added segment:

```
if [ -f "${HOME}/.todo.sh" ] ; then
  source "${HOME}/.todo.sh"
fi
```

Then create this content in ".todo.sh":
```
#!/bin/bash
TODO=/cygdrive/c/Data/Dropbox/todo
PATH=$TODO/:$PATH
source $TODO/todo_completion
alias t="$TODO/todo.sh -t"
t list
```

**OS X**
.bash_profile
```
source ./.todo.sh
```

.todo.sh
```
TODO=/Users/mmccarn/Dropbox/todo
PATH=$TODO/:$PATH
alias t="$TODO/todo.sh -t"
source $TODO/todo_completion
t list
```

**Comment by inkarkat** [comment]
The `todo.cfg` is just a Bash script; it is sourced from `todo.sh`. Though it usually just contains the `export TODO_...=...` configurations, you can add logic, conditionals, etc., like this test for `$HOSTNAME`:

    if [ "$HOSTNAME" = 'ginalaptop'
        export TODO_DIR="/Users/gina/Documents/todo"
    else
        export TODO_DIR="/home/gina/todo"
    fi

**Comment by karbassi** [comment]
Closing since multiple working solutions have been given.
