### ISSUE TITLE
CRLF after any @c/+prj counts as distinct @c or +prj

### ISSUE THREAD

**Issue by LarfAndAHarf** [todotxt/todo.txt-cli#260]
bug
CRLF line endings, iff immediately following a category or project, mess up the cat/proj parsing (and perhaps other things).
TODO.TXT Command Line Interface v2.11.0,  via brew on macOS Sierra & High Sierra, bash 3.2.57

**What is the current behavior?**
Demo todo.txt file with categories and projects alternately both at the end of a line or not:
```
$ todo.sh ls
2 inform Анастаси́я of +reorg progress @work
1 switch @work tasks to todo +reorg
--
TODO: 2 of 2 tasks shown
$ todo.sh lsc
@work
@work
$ todo.sh lsprj
+reorg
+reorg
```
Check the format of the file:
```
$ file $todofile
…path/todo.txt: UTF-8 Unicode text, with CRLF line terminators
```
Aha, it's UTF8, but has Windows line-endings. Strip the endings from DOS(/Windows) back to UNIX:
```
$ perl -pi -e 's/\r\n/\n/g' $todofile
```
Check that the CRLFs are gone:
```
$ file $todofile
…path/todo.txt: UTF-8 Unicode text
```
now that the CRLFs are gone, lets check the @c and +prj lists again:
```
$ todo.sh lsc
@work
$ todo.sh lsprj
+reorg
$ #back to normal
```

**Comment by inkarkat** [comment]
Being a Bash application, todo.txt only supports the native (LF) line endings. As you've noticed, using Windows (CR-LF) ones "mostly" works, but shows strange effects. To me, that's not a bug, but intended behavior. Of course, it would be nice if todo.txt could transparently handle all kinds of line endings. However, I think that would be an uphill battle, because most of the various _add-ons_ would have to be adapted, too! (todo.txt does not offer much in terms on an internal interface for add-ons, so most perform the same low level text operations (with `sed` and `grep`) that todo.txt does.)

Furthermore, I can't think of a compelling reason what would be the benefit of support for flexible line endings, and you also didn't mention your motivation for using CR-LF. Most external text editors can detect the used type of line endings, and I think most other todo.txt clients default to LF-line endings for compatibility, or at least have a configuration option for that. (For example, the Android _simpletask_ app that's more or less the successor of the discontinued todo.txt app has a _Windows-friendly line breaks_ option to control that.)
