### ISSUE TITLE
Add option to specify priority when adding new item

### ISSUE THREAD

**Issue by xstefank** [todotxt/todo.txt-cli#283]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When adding new todo item and prioritizing it somehow it's currently two steps (commands) process.

**What is the expected behavior?**
Allow to specify priority when adding new item so something like this will be possible:
`t a "New important TODO" A` which results into
`(A) New important TODO`

**Which versions todo.sh are you using?**
v2.11.0

**Comment by inkarkat** [comment]
I'm not sure whether this should be added to the core list of commands, because:

1. It's not an elementary command, and whether it's used (at all) highly depends on one's personal workflow.
1. It can easily be built; in fact, it's one of the examples in [Creating Add ons: Examples](https://github.com/todotxt/todo.txt-cli/wiki/Creating-Add-ons:-Examples). I also have such [addpri add-on](https://github.com/inkarkat/todo.txt-cli-ex/blob/master/actions/addpri) in my extensions, if you want a ready-made implementation.

**Comment by xstefank** [comment]
Thanks @inkarkat, I didn't know about add-ons. I will give this a try.

**Comment by xstefank** [comment]
@inkarkat Add-ons are exactly covering my use-case. Thank you for the pointer. I agree that this is not necessary as an elementary command so closing this issue. Thank you.
