### ISSUE TITLE
Missing context color highlighting at line ending

### ISSUE THREAD

**Issue by SebastianVomMeer** [todotxt/todo.txt-cli#287]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

When a todo is added with a text editor and the todo ends with a context and a line break without a space in between, the color highlighting of the context does not work.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Configure color support for contexts. 
2. Add the following line to your todo file with a text editor: `test @dev\n`. 
3. List your tasks: `todo.sh ls`

**What is the expected behavior?**

The context `@dev` should be highlighted with the specified color. But it has the same color as the rest of the line.

If you add a space before the line break it seems to work as expected. If you add the task with `todo.sh add "test @dev"` it seems to work, too, even though it doesn't seem to add a space before the line break.

**Which versions todo.sh are you using?**
> Run `todo.sh -V`
TODO.TXT Command Line Interface v2.11.0

**Which Operating System are you using?**
Ubuntu 18.04.3 LTS

**Which version of bash are you using?**
> Run `bash --version`
GNU bash, Version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by inkarkat** [comment]
Please find out what's the difference in the `todo.txt` file between `todo.sh add` (where highlighting works) and the manual editing (where it doesn't). There has to be a difference, and because todo.txt is text-based, it can't be so difficult to find. If necessary, you can compare (e.g. with `diff`) the hexdumps (obtained via e.g. `hd` / `hexdump`). I suspect that your text editor is doing something strange with the file (but it doesn't seem to be just an added carriage return). If that's too difficult for you, at least attach an affected dummy todo.txt here.

**Comment by SebastianVomMeer** [comment]
This is my test file (hopefully it is not converted by the upload somehow):
[todo.txt](https://github.com/todotxt/todo.txt-cli/files/3611906/todo.txt)

In my opinion it seems to be an issue with carriage return. I use an Android App called Simpletask which seems to enable Windows line breaks by default.

**Comment by inkarkat** [comment]
I can reproduce it now; the problem is indeed with the additional carriage return characters. (I didn't see this beforehand because my custom filter was still active.)

The regexp pattern that does the `+project` and `@context` highlighting could be tweaked, but I'm afraid that there likely are other places where this would cause inconsistencies, and it would start a tedious and lengthy hunt for each and every one of those. Therefore, I'd rather keep the current limitation to Unix-style line endings if you use the `todo.sh` tool.

Most (non-CLI) clients have an option to influence the line ending style. In Simpletask, this can be configured via _Settings &gt; Other &gt; ☐ Windows-friendly line breaks_. I'd suggest you disable this option, and all should be well. As long as the line endings are consistent (and a tool like `dos2unix` could be used to ensure that), most other text editors (well, except Windows' Notepad I think) should also detect and properly handle the Unix-style line endings.
