### ISSUE TITLE
How to disable todo.txt.bak file?

### ISSUE THREAD

**Issue by poorlet** [todotxt/todo.txt-cli#327]
todo.txt.bak file always show up after anything edited with todo.txt-cli, so is there anything config to turn it off, or auto clean it up?

**Comment by inkarkat** [comment]
The backup file is left to be able to manually restore the original file after a mistake (e.g. an accidental deletion of task(s)), or environment problems (like running out of disk space or a corrupted write).

I've given a configuration snippet in #312 to turn this off. What's your motivation for requesting this? Can't you just ignore those backup files (knowning they might one day save you from data loss)?

If there's a valid reason for turning off backups (now that this is the second time I've encountered this request), we could introduce a configuration option (e.g. `TODOTXT_BACKUP_EXT=.bak`) instead of hard-coding it. This would make the reconfiguration both more discoverable (as the variable is mentioned in the verbose help) and simpler (just a one-liner). However, add-ons still have this hard-coded, so it would be a less complete solution than the snippet above.
