### ISSUE TITLE
XDG Base Directory Specification Compliance

### ISSUE THREAD

**Issue by Ekstropiya** [todotxt/todo.txt-cli#342]
At the moment, todo.txt creates it's config file in ``$HOME/.todo/config``. Creating configuration folders/files in the user's home directory can make it very cluttered. The [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) provides a solution to this by proposing a standard configuration directory: ``$HOME/.config`` by default (some operating systems set this to something else). It would be great to have at least one less configuration folder in our home directories.

**Comment by inkarkat** [comment]
The code supports `XDG_CONFIG_HOME` for the configuration and custom actions since [this commit](https://github.com/todotxt/todo.txt-cli/commit/34b61354151dd332f3853c7bc58a58bc1e3933cd) (submitted in 2015 as #154, merged in 2017). However, the whole configuration alternatives seem to be under-documented, and mostly only the original default location is mentioned.

**Comment by Ekstropiya** [comment]
Interesting. It didn't seem to work on my machine. I'll try reinstalling and check my environment variables. Sorry, I should've checked the source to see if this wasn't already implemented.

**Comment by karbassi** [comment]
Should we keep this issue open to focus on documentation or close it?

Thoughts @inkarkat
