### ISSUE TITLE
How to change the fonts in conky for the todo.txt-cli items?

### ISSUE THREAD

**Issue by blogdemoi** [todotxt/todo.txt-cli#344]
**What is the current behavior?**
I am using todo.txt-cli with conky.

**What is the expected behavior?**
I would like to change the fonts in conky for the todo.txt-cli items. How can I do that? Thank you.

**Which versions todo.sh are you using?**
TODO.TXT Command Line Interface v2.12.0

**Which Operating System are you using?**
Manjaro Xfce

**Which version of bash are you using?**
I am using zsh with oh my zsh

**Comment by inkarkat** [comment]
I have this in my `~/.conkyrc` file (using legacy syntax):

```
use_xft yes
xftfont Courier:size=10
```

As this problem is only indirectly related to `todo.sh`, I'm closing this issue. Please [search the Internet](https://letmegooglethat.com/?q=conky+change+font) or use the [Conky project](https://github.com/brndnmtthws/conky)'s issue tracker if you need further assistance.
