### ISSUE TITLE
Run todo.sh through ShellCheck

### ISSUE THREAD

**Issue by a1346054** [todotxt/todo.txt-cli#345]
**Do you want to request a *feature* or report a *bug*?**
This is a feature request.

**What is the current behavior?**
ShellCheck detects many warnings and possible issues in todo.sh

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Use https://www.shellcheck.net/ or the command-line equivalent tool to fix warnings in todo.sh

**What is the expected behavior?**
No warnings detected using ShellCheck, or if the warnings are not relevant then they should be masked for ShellCheck

**Which versions todo.sh are you using?**
2.12

**Which Operating System are you using?**
Linux

**Comment by inkarkat** [comment]
You're very welcome to submit a pull request that addresses (some / all) shellcheck errors!

I wouldn't call this a feature, though, because we're using the test suite to verify the quality of the code. Consistent code style would be a nice non-functional requirement, but given the history of this tool, this isn't a priority.

**Comment by karbassi** [comment]
Fixed in #350

**Comment by a1346054** [comment]
There are more issues identified through shellcheck that should be fixed. If you don't wish to use the commandline tool, the web interface works just as well https://www.shellcheck.net/ . Just put the whole todo.sh script into it.
