### ISSUE TITLE
Not working on MacOS 11.4

### ISSUE THREAD

**Issue by mroberts1** [todotxt/todo.txt-cli#348]
**What is the current behavior?**

Unable to write any list items to todo.txt in "/Users/usrname/Documents/todo"

**What is the expected behavior?**

Writing a list item to todo.txt

**Which versions todo.sh are you using?**
> Run `todo.sh -V`

Unable to find todo.sh

**Which Operating System are you using?**

MacOS 11.4

**Which version of bash are you using?**
> Run `bash --version`

.zshrc

**Comment by inkarkat** [comment]
It's good that you've asked on the [Gitter todotxt channel](https://gitter.im/todotxt/Lobby) in parallel; the information given here is not enough to recognize the underlying issue. As this very likely is a configuration issue on your side, I'm closing the issue here and hope that this can be resolved through Gitter.
